# Generated by Django 5.0.6 on 2024-06-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='content_id',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='transactionitem',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
